config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted,
  # simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here,
  # as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'home#index'
    get 'index',                    to: 'home#index'
    resources :products,            only: [:index, :show]
    resources :categories,          only: [:show]

    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/filter.rb
class Spree::Filter
  attr_reader :taxon, :option_value, :display_type

  def initialize(params = {})
    @taxon        = params[:taxon].presence
    @option_value = params[:option_value].presence
    @display_type = params[:display_type] || 'grid'
  end

  def filtered_products
    scopes = base_scope(taxon: @taxon)
    scopes = scopes.search_by_option_value(@option_value) if @option_value
    scopes
  end

  def grid_display?
    display_type == 'grid'
  end

  private

  def base_scope(taxon: nil)
    scope = Spree::Product.includes_price_image.distinct
    taxon.present? ? scope.in_taxon(taxon) : scope
  end
end

app/models/spree/option_type_decorator.rb
Spree::OptionType.class_eval do
  class << self
    def search_by_names(names_array)
      find_by(name: names_array)
    end

    def tshit_color
      search_by_names('tshirt-color')
    end

    def tshit_size
      search_by_names('tshirt-size')
    end
  end
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
  def search_products
    ids = Spree::Product.with_option_value(option_type_id, name).pluck(:id)
    Spree::Product.where(id: ids)
  end

  def count_products
    search_products.count
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :includes_price_image, -> { includes(master: [:default_price, :images]) }

  def self.search_by_option_value(option_value)
    joins(variants: :option_values).where(spree_option_values: { id: option_value })
  end

  def related_products
    if taxons.present?
      Spree::Product.in_taxons(taxons).where.not(id: id).distinct
    else
      Spree::Product.none
    end
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  def self.search_by_names(names_array)
    where(name: names_array)
  end
end

app/models/spree/taxonomies_decorator.rb
Spree::Taxonomy.class_eval do
  def taxons_list
    taxons = self.taxons
    if taxons
      taxons.select { |taxon| taxon.parent_id.present? }
    else
      []
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    main_app.potepan_path
  end

  def after_sign_out_path_for(resource)
    main_app.potepan_path
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :set_sidebar, only: [:show]

  def show
    @taxon          = Spree::Taxon.find(params[:id])
    @product_filter = Spree::Filter.new(filter_params.merge(taxon: @taxon))
    @products       = @product_filter.filtered_products
  end

  private

  def filter_params
    params.permit(:option_value, :display_type)
  end

  def set_sidebar
    @taxonomies   = Spree::Taxonomy.includes(:taxons)
    @search_color = Spree::OptionType.tshit_color
    @search_size  = Spree::OptionType.tshit_size
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  FIRST_DAY_OF_NEW_ARRIVAL_PRODUCTS = 1.month.ago                  # 暫定的に1ヶ月間を新着商品期間に設定
  MAX_NUMBER_OF_NEW_ARRIVAL_PRODUCTS_DISPLAY = 4                   # 暫定的に新着商品の表示個数を設定
  THREE_POPULAR_TAXONS = ['Categories', 'Clothing', 'Bags'].freeze # 暫定的に人気商品を３つ設定

  def index
    @popular_taxons = Spree::Taxon.search_by_names(THREE_POPULAR_TAXONS)
    @new_products   = Spree::Product.where('available_on >= ?', FIRST_DAY_OF_NEW_ARRIVAL_PRODUCTS).
      includes(master: :default_price).sample(MAX_NUMBER_OF_NEW_ARRIVAL_PRODUCTS_DISPLAY)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  before_action :set_sidebar, only: [:index]
  MAX_NUMBER_OF_DISPLAY_PRODUCTS = 4

  def index
    @product_filter = Spree::Filter.new(filter_params)
    @products       = @product_filter.filtered_products
  end

  def show
    @product = Spree::Product.find(params[:id])
    @related_products =
      @product.related_products.
        includes_price_image.
        sample(MAX_NUMBER_OF_DISPLAY_PRODUCTS)
  end

  private

  def filter_params
    params.permit(:option_value, :display_type)
  end

  def set_sidebar
    @taxonomies   = Spree::Taxonomy.includes(:taxons)
    @search_color = Spree::OptionType.tshit_color
    @search_size  = Spree::OptionType.tshit_size
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title: '')
    base_title = "Potepanec"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def resource_name
    :spree_user
  end

  def resource
    @resource ||= Spree::User.new
  end
end

app/helpers/filter_helper.rb
module FilterHelper
  def display_type
    params[:display_type] || 'grid'
  end

  def active?(type)
    'active' if type == display_type
  end

  def categories_controller?
    controller.controller_name == 'categories'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application',
      'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.css', media: 'all' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', media: "all" %>
    <%= render 'potepan/shared/meta_tags' %>
    <title><%= full_title(page_title: yield(:title)) %></title>
    <%= render 'potepan/shared/shim' %>
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'potepan/shared/header' %>
      <%= yield %>
      <%= render 'potepan/shared/footer' %>
    </div>
    <%= render 'potepan/shared/login_modal' %>
    <%= render 'potepan/shared/signup_modal' %>
    <%= render 'potepan/shared/quick_view' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render 'potepan/shared/light_section', { content_name: @taxon.name } %>
<%= render 'potepan/shared/show_products', { taxonomies:@taxonomies,
  search_color: @search_color, search_size: @search_size, product_filter: @product_filter, products: @products } %>

app/views/potepan/home/_new_products.html.erb
<div class="row featuredProducts">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>新着商品</h4>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="owl-carousel featuredProductsSlider">
      <% new_products.each do |new_product| %>
        <div class="slide">
          <%= link_to potepan_product_path(new_product.id) do %>
            <div class="productImage clearfix">
              <%= image_tag(new_product.display_image.attachment(:product),
                alt: new_product.display_image.attachment_file_name ) %>
            </div>
            <div class="productCaption clearfix">
              <h5><%= new_product.name %></h5>
              <h3><%= new_product.display_price %></h3>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/home/_popular_taxons.html.erb
<div class="row featuredCollection">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>人気カテゴリー</h4>
    </div>
  </div>
  <% popular_taxons.each do |popular_taxon| %>
    <div class="col-sm-4 col-xs-12">
      <div class="thumbnail">
        <%= link_to potepan_category_path(popular_taxon.id) do %>
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-#{popular_taxon.name}.jpg",
              alt: "feature-collection-#{popular_taxon.name}-image" ) %>
            <div class="masking"><div class="btn viewBtn">View <%= popular_taxon.name %></div></div>
          </div>
          <div class="caption">
            <h4><%= popular_taxon.name %></h4>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/home/index.html.erb
<!-- BANNER -->
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <% if @popular_taxons.present? %>
      <%= render 'popular_taxons', { popular_taxons: @popular_taxons } %>
    <% end %>
    <% if @new_products.present? %>
      <%= render 'new_products', { new_products: @new_products } %>
    <% end %>
  </div>
</section>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |related_product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(related_product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag(related_product.display_image.attachment(:product),
              alt: related_product.display_image.attachment_file_name ) %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= related_product.name %></h5>
            <h3><%= related_product.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/index.html.erb
<% provide(:title, "Filter Products") %>
<%= render 'potepan/shared/light_section', { content_name: "Filter Priducts" } %>
<%= render 'potepan/shared/show_products', { taxonomies:@taxonomies,
  search_color: @search_color, search_size: @search_size, product_filter: @product_filter, products: @products } %>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<%= render 'potepan/shared/light_section', { content_name: @product.name } %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_with_index do |image, i| %>
                  <div class="item <%= "active" if i.zero? %>" data-thumb="<%= i %>">
                    <%= image_tag(image.attachment(:large), alt: image.attachment_file_name) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, i| %>
                    <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                      <%= image_tag(image.attachment(:small), alt: image.attachment_file_name) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to(potepan_category_path(@product.taxons.ids.first)) do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <% if @product.variants.present? %>
              <span class="quick-drop">
                <%= select_tag "guiest_id3", options_from_collection_for_select(
                  @product.variants, :id, :options_text), class: "select-drop" %>
              </span>
            <% end %>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="#" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if @related_products.present? %>
      <%= render 'related_products', { related_products: @related_products } %>
    <% end %>
  </div>
</section>

app/views/potepan/sample/checkout_complete.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Order Completed - BIGBAG Store</title>

    <!-- PLUGINS CSS STYLE -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

    <!-- CUSTOM CSS -->
    <link href="css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="css/colors/default.css" id="option_color">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="main-wrapper">

      <!-- HEADER -->
      <div class="header clearfix">

        <!-- TOPBAR -->
        <div class="topBar">
          <div class="container">
            <div class="row">
              <div class="col-md-6 hidden-sm hidden-xs">
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                </ul>
              </div>
              <div class="col-md-6 col-xs-12">
                <ul class="list-inline pull-right">
                  <li><!-- <span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span> --></li>
                  <li class="dropdown searchBox">
                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <form  id="form01" action="product-grid-left-sidebar.html" method="post">
                      <li>
                        <span class="input-group">
                          <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                          <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                        </span>
                      </li>
                      </form>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- NAVBAR -->
        <nav class="navbar navbar-main navbar-default" role="navigation">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html"><%= image_tag("logo.png") %></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li class=""><a href="index.html">Home</a></li>
                <li class="dropdown megaDropMenu">
                  <a href="product-grid-left-sidebar.html" class="dropdown-toggle">Shop</b></a>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div>
        </nav>

      </div>

      <!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-xs-6">
              <div class="page-title">
                <h2>thanks message</h2>
              </div>
            </div>
            <div class="col-xs-6">
              <ol class="breadcrumb pull-right">
                <li>
                  <a href="index.html">Home</a>
                </li>
                <li class="active">thanks message</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix setp5">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="thanksContent">
                <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
                <h3>Shipping Details</h3>
                <div class="thanksInner">
                  <div class="row">
                    <div class="col-sm-6 col-xs-12 tableBlcok">
                      <address>
                        <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                        <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                        <span>Phone:</span> +884 5452 6432
                      </address>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                      <div class="well">
                        <h2><small>Order ID</small>9547</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- FOOTER -->
      <!-- COPY RIGHT -->
      <div id="footer" class="copyRight clearfix">
        <div class="container">
          <div class="row">
            <div class="col-sm-7 col-xs-12">
              <p>&copy; 2016-<%= Time.now.year %> Copyright Potepan Store .</p>
            </div>
            <div class="col-sm-5 col-xs-12">
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- LOGIN MODAL -->
    <div class="modal fade" id="login" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">log in</h3>
          </div>
          <div class="modal-body">
            <form action="" method="POST" role="form">
              <div class="form-group">
                <label for="login-email">Enter Email</label>
                <input type="email" class="form-control" id="login-email">
              </div>
              <div class="form-group">
                <label for="login-password">Password</label>
                <input type="password" class="form-control" id="login-password">
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember Me
                </label>
              </div>
              <button type="submit" class="btn btn-primary btn-block">log in</button>
              <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- SIGN UP MODAL -->
    <div class="modal fade" id="signup" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">Create an account</h3>
          </div>
          <div class="modal-body">
            <form action="" method="POST" role="form">
              <div class="form-group">
                <label for="signup-email">Enter Email</label>
                <input type="email" class="form-control" id="signup-email">
              </div>
              <div class="form-group">
                <label for="signup-password">Password</label>
                <input type="password" class="form-control" id="signup-password">
              </div>
              <div class="form-group">
                <label for="signup-password-confirmation">Confirm Password</label>
                <input type="password" class="form-control" id="signup-password-confirmation">
              </div>
              <button type="submit" class="btn btn-primary btn-block">Sign up</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/potepan/shared/_filter.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
  </div>
    <div class="col-xs-6">
      <div class="btn-group pull-right" role="group">
        <% ["grid", "list"].each do |type|  %>
          <% if categories_controller? %>
            <%= link_to potepan_category_path(params[:id], option_value: product_filter.option_value, display_type: type),
              class: "btn btn-default #{active?(type)}" do %>
              <i class="fa fa-th" aria-hidden="true"></i><span><%= type %></span></button>
            <% end %>
          <% else %>
            <%= link_to potepan_products_path(option_value: product_filter.option_value, display_type: type),
              class: "btn btn-default #{active?(type)}" do %>
              <i class="fa fa-th" aria-hidden="true"></i><span><%= type %></span></button>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/potepan/shared/_meta_tags.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/potepan/shared/_option_types_filter.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">FILTER BY <%= option_type.presentation %></div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% option_type.option_values.each do |option_value| %>
        <li>
          <%= link_to(potepan_products_path(option_value: option_value)) do %>
            <%= option_value.name %><span>(<%= option_value.count_products %>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/shared/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">Categories</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% taxonomies.each do |taxonomy| %>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#<%= taxonomy.name %>">
                <%= taxonomy.name %><i class="fa fa-plus"></i></a>
              <ul id="<%= taxonomy.name %>" class="collapse collapseItem">
                <% taxonomy.taxons_list.each do |taxon| %>
                  <li>
                    <%= link_to potepan_category_path(taxon.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i>
                      <%= taxon.name %><span> (<%= taxon.all_products.count %>)</span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <% if search_color.present? %>
    <%= render 'potepan/shared/option_types_filter', { option_type: search_color } %>
  <% end %>
  <% if search_size.present? %>
    <%= render 'potepan/shared/option_types_filter', { option_type: search_size } %>
  <% end %>
</div>